# Generated by Django 5.2.4 on 2025-07-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('Identificador', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Ano_Implantacao', models.IntegerField(blank=True, null=True)),
                ('Regional', models.CharField(blank=True, max_length=100, null=True)),
                ('Estacao_BdRaf', models.CharField(blank=True, max_length=100, null=True)),
                ('COD_IBGE', models.IntegerField(blank=True, null=True)),
                ('Municipio', models.CharField(blank=True, max_length=200, null=True)),
                ('Projeto_CAPEX', models.CharField(blank=True, max_length=200, null=True)),
                ('Sub_Projeto_CAPEX', models.CharField(blank=True, max_length=200, null=True)),
                ('SI_CAPEX', models.CharField(blank=True, max_length=100, null=True)),
                ('Reserva_1', models.CharField(blank=True, max_length=200, null=True)),
                ('Reserva_2', models.CharField(blank=True, max_length=200, null=True)),
                ('Reserva_3', models.CharField(blank=True, max_length=200, null=True)),
                ('Reserva_4', models.CharField(blank=True, max_length=200, null=True)),
                ('Reserva_5', models.CharField(blank=True, max_length=200, null=True)),
                ('QUALIDADE_PREENCHIMENTO', models.CharField(blank=True, max_length=50, null=True)),
                ('CAPEX', models.FloatField(blank=True, null=True)),
                ('OS_WF', models.CharField(blank=True, max_length=100, null=True)),
                ('Km_Projeto_Executado', models.FloatField(blank=True, null=True)),
                ('Km_Construido', models.FloatField(blank=True, null=True)),
                ('Data_Protocolo_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Construcao_Parcial_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Req_Gen_Plan', models.DateField(blank=True, null=True)),
                ('Req_Gen_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Projeto_Executivo_Plan', models.DateField(blank=True, null=True)),
                ('Projeto_Executivo_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Licenciamento_Plan', models.DateField(blank=True, null=True)),
                ('Licenciamento_Real', models.CharField(default='Não realizado', max_length=50)),
                ('MOS_Plan', models.DateField(blank=True, null=True)),
                ('MOS_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Swap_Plan', models.DateField(blank=True, null=True)),
                ('Swap_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Construcao_Total_Plan', models.DateField(blank=True, null=True)),
                ('Construcao_Total_Real', models.CharField(default='Não realizado', max_length=50)),
                ('RFI_Plan', models.DateField(blank=True, null=True)),
                ('RFI_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Entroncado_Plan', models.DateField(blank=True, null=True)),
                ('Entroncado_Real', models.CharField(default='Não realizado', max_length=50)),
                ('Documentacao_Plan', models.DateField(blank=True, null=True)),
                ('Documentacao_Real', models.CharField(default='Não realizado', max_length=50)),
                ('GP_Plan', models.DateField(blank=True, null=True)),
                ('GP_Real', models.CharField(default='Não realizado', max_length=50)),
                ('dataAtualizacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
