# Generated by Django 5.2.4 on 2025-07-25 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='dataAtualizacao',
            new_name='data_atualizacao',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='Reserva_1',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='Reserva_2',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='Reserva_3',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='Reserva_4',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='Reserva_5',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ultima_atualizacao_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Construcao_Parcial_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Construcao_Total_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Data_Protocolo_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Documentacao_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Entroncado_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='GP_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Licenciamento_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='MOS_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Projeto_CAPEX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Projeto_Executivo_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='RFI_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Req_Gen_Real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Sub_Projeto_CAPEX',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='Swap_Real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
