# Generated by Django 5.2.4 on 2025-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_rename_dataatualizacao_projeto_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PnfoGeral',
            fields=[
                ('Identificador', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('Regional', models.CharField(blank=True, max_length=100, null=True)),
                ('Estacao_BdRaf', models.CharField(blank=True, max_length=100, null=True)),
                ('COD_IBGE', models.IntegerField(blank=True, null=True)),
                ('Municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('Projeto_CAPEX', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Projeto_CAPEX', models.CharField(blank=True, max_length=100, null=True)),
                ('SI_CAPEX', models.CharField(blank=True, max_length=100, null=True)),
                ('Ano_Implantacao', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
