# Generated by Django 5.2.4 on 2025-08-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_pnfogeral'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='foi_notificado',
            field=models.BooleanField(default=False),
        ),
    ]
