# Generated by Django 5.2.4 on 2025-08-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_projeto_foi_notificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='CAPEX',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
